image: node:10.16

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm run lint
   - npm run test-ci

# stages:
#   - test
#   - deploy

# test-ci:
#   stage: test
#   tags:
#     - runner-docker
#   image: node:10.16
#   cache:
#     paths:
#       - node_modules/
#   services:
#     - postgres:11.3
#   variables:
#     POSTGRES_DB: property_test
#     POSTGRES_USER: property_ci
#     POSTGRES_PASSWORD: property_ci
#   script:
#     - npm install
#     - npx knex migrate:latest --env ci
#     - npm run lint
#     - NODE_ENV=ci npm run test-ci

# deploy-staging:
#   stage: deploy
#   tags:
#     - runner-deploy
#   variables:
#     IMAGE_NAME: property-service
#     GIT_STRATEGY: clone
#   script:
#     - docker build -t $IMAGE_NAME .
#     - cat "$GCLOUD_SERVICE_KEY" | docker login -u _json_key --password-stdin https://asia.gcr.io
#     - docker tag $IMAGE_NAME asia.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:latest
#     - docker push asia.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:latest
#     - /home/gitlab-runner/staging-scripts/deploy.sh
#   only:
#     - dev

