version: "3.7"
services:
  base-service:
    env_file: dev.docker-compose.env
    container_name: "base-service"
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: docker/entrypoint.sh
    networks:
      dev_network:
networks:
  dev_network:
    external: true
